// Code generated by ent, DO NOT EDIT.

package smsorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the smsorder type in the database.
	Label = "sms_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldServiceType holds the string denoting the service_type field in the database.
	FieldServiceType = "service_type"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldHeroSmsID holds the string denoting the hero_sms_id field in the database.
	FieldHeroSmsID = "hero_sms_id"
	// FieldSmsContent holds the string denoting the sms_content field in the database.
	FieldSmsContent = "sms_content"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPendingAt holds the string denoting the pending_at field in the database.
	FieldPendingAt = "pending_at"
	// Table holds the table name of the smsorder in the database.
	Table = "sms_orders"
)

// Columns holds all SQL columns for smsorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrderNo,
	FieldServiceType,
	FieldPhoneNumber,
	FieldHeroSmsID,
	FieldSmsContent,
	FieldStatus,
	FieldPendingAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// DefaultServiceType holds the default value on creation for the "service_type" field.
	DefaultServiceType string
	// ServiceTypeValidator is a validator for the "service_type" field. It is called by the builders before save.
	ServiceTypeValidator func(string) error
	// DefaultPhoneNumber holds the default value on creation for the "phone_number" field.
	DefaultPhoneNumber string
	// PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	PhoneNumberValidator func(string) error
	// DefaultHeroSmsID holds the default value on creation for the "hero_sms_id" field.
	DefaultHeroSmsID string
	// HeroSmsIDValidator is a validator for the "hero_sms_id" field. It is called by the builders before save.
	HeroSmsIDValidator func(string) error
	// DefaultSmsContent holds the default value on creation for the "sms_content" field.
	DefaultSmsContent string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the SmsOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByServiceType orders the results by the service_type field.
func ByServiceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceType, opts...).ToFunc()
}

// ByPhoneNumber orders the results by the phone_number field.
func ByPhoneNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumber, opts...).ToFunc()
}

// ByHeroSmsID orders the results by the hero_sms_id field.
func ByHeroSmsID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeroSmsID, opts...).ToFunc()
}

// BySmsContent orders the results by the sms_content field.
func BySmsContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSmsContent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPendingAt orders the results by the pending_at field.
func ByPendingAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingAt, opts...).ToFunc()
}
