// Code generated by ent, DO NOT EDIT.

package smsorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldOrderNo, v))
}

// ServiceType applies equality check predicate on the "service_type" field. It's identical to ServiceTypeEQ.
func ServiceType(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldServiceType, v))
}

// PhoneNumber applies equality check predicate on the "phone_number" field. It's identical to PhoneNumberEQ.
func PhoneNumber(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPhoneNumber, v))
}

// HeroSmsID applies equality check predicate on the "hero_sms_id" field. It's identical to HeroSmsIDEQ.
func HeroSmsID(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldHeroSmsID, v))
}

// SmsContent applies equality check predicate on the "sms_content" field. It's identical to SmsContentEQ.
func SmsContent(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldSmsContent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldStatus, v))
}

// PendingAt applies equality check predicate on the "pending_at" field. It's identical to PendingAtEQ.
func PendingAt(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPendingAt, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldRetryCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// ServiceTypeEQ applies the EQ predicate on the "service_type" field.
func ServiceTypeEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldServiceType, v))
}

// ServiceTypeNEQ applies the NEQ predicate on the "service_type" field.
func ServiceTypeNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldServiceType, v))
}

// ServiceTypeIn applies the In predicate on the "service_type" field.
func ServiceTypeIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldServiceType, vs...))
}

// ServiceTypeNotIn applies the NotIn predicate on the "service_type" field.
func ServiceTypeNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldServiceType, vs...))
}

// ServiceTypeGT applies the GT predicate on the "service_type" field.
func ServiceTypeGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldServiceType, v))
}

// ServiceTypeGTE applies the GTE predicate on the "service_type" field.
func ServiceTypeGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldServiceType, v))
}

// ServiceTypeLT applies the LT predicate on the "service_type" field.
func ServiceTypeLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldServiceType, v))
}

// ServiceTypeLTE applies the LTE predicate on the "service_type" field.
func ServiceTypeLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldServiceType, v))
}

// ServiceTypeContains applies the Contains predicate on the "service_type" field.
func ServiceTypeContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldServiceType, v))
}

// ServiceTypeHasPrefix applies the HasPrefix predicate on the "service_type" field.
func ServiceTypeHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldServiceType, v))
}

// ServiceTypeHasSuffix applies the HasSuffix predicate on the "service_type" field.
func ServiceTypeHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldServiceType, v))
}

// ServiceTypeEqualFold applies the EqualFold predicate on the "service_type" field.
func ServiceTypeEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldServiceType, v))
}

// ServiceTypeContainsFold applies the ContainsFold predicate on the "service_type" field.
func ServiceTypeContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldServiceType, v))
}

// PhoneNumberEQ applies the EQ predicate on the "phone_number" field.
func PhoneNumberEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPhoneNumber, v))
}

// PhoneNumberNEQ applies the NEQ predicate on the "phone_number" field.
func PhoneNumberNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldPhoneNumber, v))
}

// PhoneNumberIn applies the In predicate on the "phone_number" field.
func PhoneNumberIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldPhoneNumber, vs...))
}

// PhoneNumberNotIn applies the NotIn predicate on the "phone_number" field.
func PhoneNumberNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldPhoneNumber, vs...))
}

// PhoneNumberGT applies the GT predicate on the "phone_number" field.
func PhoneNumberGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldPhoneNumber, v))
}

// PhoneNumberGTE applies the GTE predicate on the "phone_number" field.
func PhoneNumberGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldPhoneNumber, v))
}

// PhoneNumberLT applies the LT predicate on the "phone_number" field.
func PhoneNumberLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldPhoneNumber, v))
}

// PhoneNumberLTE applies the LTE predicate on the "phone_number" field.
func PhoneNumberLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldPhoneNumber, v))
}

// PhoneNumberContains applies the Contains predicate on the "phone_number" field.
func PhoneNumberContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldPhoneNumber, v))
}

// PhoneNumberHasPrefix applies the HasPrefix predicate on the "phone_number" field.
func PhoneNumberHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldPhoneNumber, v))
}

// PhoneNumberHasSuffix applies the HasSuffix predicate on the "phone_number" field.
func PhoneNumberHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldPhoneNumber, v))
}

// PhoneNumberIsNil applies the IsNil predicate on the "phone_number" field.
func PhoneNumberIsNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIsNull(FieldPhoneNumber))
}

// PhoneNumberNotNil applies the NotNil predicate on the "phone_number" field.
func PhoneNumberNotNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotNull(FieldPhoneNumber))
}

// PhoneNumberEqualFold applies the EqualFold predicate on the "phone_number" field.
func PhoneNumberEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldPhoneNumber, v))
}

// PhoneNumberContainsFold applies the ContainsFold predicate on the "phone_number" field.
func PhoneNumberContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldPhoneNumber, v))
}

// HeroSmsIDEQ applies the EQ predicate on the "hero_sms_id" field.
func HeroSmsIDEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldHeroSmsID, v))
}

// HeroSmsIDNEQ applies the NEQ predicate on the "hero_sms_id" field.
func HeroSmsIDNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldHeroSmsID, v))
}

// HeroSmsIDIn applies the In predicate on the "hero_sms_id" field.
func HeroSmsIDIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldHeroSmsID, vs...))
}

// HeroSmsIDNotIn applies the NotIn predicate on the "hero_sms_id" field.
func HeroSmsIDNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldHeroSmsID, vs...))
}

// HeroSmsIDGT applies the GT predicate on the "hero_sms_id" field.
func HeroSmsIDGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldHeroSmsID, v))
}

// HeroSmsIDGTE applies the GTE predicate on the "hero_sms_id" field.
func HeroSmsIDGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldHeroSmsID, v))
}

// HeroSmsIDLT applies the LT predicate on the "hero_sms_id" field.
func HeroSmsIDLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldHeroSmsID, v))
}

// HeroSmsIDLTE applies the LTE predicate on the "hero_sms_id" field.
func HeroSmsIDLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldHeroSmsID, v))
}

// HeroSmsIDContains applies the Contains predicate on the "hero_sms_id" field.
func HeroSmsIDContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldHeroSmsID, v))
}

// HeroSmsIDHasPrefix applies the HasPrefix predicate on the "hero_sms_id" field.
func HeroSmsIDHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldHeroSmsID, v))
}

// HeroSmsIDHasSuffix applies the HasSuffix predicate on the "hero_sms_id" field.
func HeroSmsIDHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldHeroSmsID, v))
}

// HeroSmsIDIsNil applies the IsNil predicate on the "hero_sms_id" field.
func HeroSmsIDIsNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIsNull(FieldHeroSmsID))
}

// HeroSmsIDNotNil applies the NotNil predicate on the "hero_sms_id" field.
func HeroSmsIDNotNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotNull(FieldHeroSmsID))
}

// HeroSmsIDEqualFold applies the EqualFold predicate on the "hero_sms_id" field.
func HeroSmsIDEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldHeroSmsID, v))
}

// HeroSmsIDContainsFold applies the ContainsFold predicate on the "hero_sms_id" field.
func HeroSmsIDContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldHeroSmsID, v))
}

// SmsContentEQ applies the EQ predicate on the "sms_content" field.
func SmsContentEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldSmsContent, v))
}

// SmsContentNEQ applies the NEQ predicate on the "sms_content" field.
func SmsContentNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldSmsContent, v))
}

// SmsContentIn applies the In predicate on the "sms_content" field.
func SmsContentIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldSmsContent, vs...))
}

// SmsContentNotIn applies the NotIn predicate on the "sms_content" field.
func SmsContentNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldSmsContent, vs...))
}

// SmsContentGT applies the GT predicate on the "sms_content" field.
func SmsContentGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldSmsContent, v))
}

// SmsContentGTE applies the GTE predicate on the "sms_content" field.
func SmsContentGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldSmsContent, v))
}

// SmsContentLT applies the LT predicate on the "sms_content" field.
func SmsContentLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldSmsContent, v))
}

// SmsContentLTE applies the LTE predicate on the "sms_content" field.
func SmsContentLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldSmsContent, v))
}

// SmsContentContains applies the Contains predicate on the "sms_content" field.
func SmsContentContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldSmsContent, v))
}

// SmsContentHasPrefix applies the HasPrefix predicate on the "sms_content" field.
func SmsContentHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldSmsContent, v))
}

// SmsContentHasSuffix applies the HasSuffix predicate on the "sms_content" field.
func SmsContentHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldSmsContent, v))
}

// SmsContentIsNil applies the IsNil predicate on the "sms_content" field.
func SmsContentIsNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIsNull(FieldSmsContent))
}

// SmsContentNotNil applies the NotNil predicate on the "sms_content" field.
func SmsContentNotNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotNull(FieldSmsContent))
}

// SmsContentEqualFold applies the EqualFold predicate on the "sms_content" field.
func SmsContentEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldSmsContent, v))
}

// SmsContentContainsFold applies the ContainsFold predicate on the "sms_content" field.
func SmsContentContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldSmsContent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldStatus, v))
}

// PendingAtEQ applies the EQ predicate on the "pending_at" field.
func PendingAtEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPendingAt, v))
}

// PendingAtNEQ applies the NEQ predicate on the "pending_at" field.
func PendingAtNEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldPendingAt, v))
}

// PendingAtIn applies the In predicate on the "pending_at" field.
func PendingAtIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldPendingAt, vs...))
}

// PendingAtNotIn applies the NotIn predicate on the "pending_at" field.
func PendingAtNotIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldPendingAt, vs...))
}

// PendingAtGT applies the GT predicate on the "pending_at" field.
func PendingAtGT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldPendingAt, v))
}

// PendingAtGTE applies the GTE predicate on the "pending_at" field.
func PendingAtGTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldPendingAt, v))
}

// PendingAtLT applies the LT predicate on the "pending_at" field.
func PendingAtLT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldPendingAt, v))
}

// PendingAtLTE applies the LTE predicate on the "pending_at" field.
func PendingAtLTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldPendingAt, v))
}

// PendingAtIsNil applies the IsNil predicate on the "pending_at" field.
func PendingAtIsNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIsNull(FieldPendingAt))
}

// PendingAtNotNil applies the NotNil predicate on the "pending_at" field.
func PendingAtNotNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotNull(FieldPendingAt))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldRetryCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.NotPredicates(p))
}
