// Code generated by ent, DO NOT EDIT.

package smsorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldOrderNo, v))
}

// PhoneNumber applies equality check predicate on the "phone_number" field. It's identical to PhoneNumberEQ.
func PhoneNumber(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPhoneNumber, v))
}

// SmsContent applies equality check predicate on the "sms_content" field. It's identical to SmsContentEQ.
func SmsContent(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldSmsContent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// PhoneNumberEQ applies the EQ predicate on the "phone_number" field.
func PhoneNumberEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldPhoneNumber, v))
}

// PhoneNumberNEQ applies the NEQ predicate on the "phone_number" field.
func PhoneNumberNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldPhoneNumber, v))
}

// PhoneNumberIn applies the In predicate on the "phone_number" field.
func PhoneNumberIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldPhoneNumber, vs...))
}

// PhoneNumberNotIn applies the NotIn predicate on the "phone_number" field.
func PhoneNumberNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldPhoneNumber, vs...))
}

// PhoneNumberGT applies the GT predicate on the "phone_number" field.
func PhoneNumberGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldPhoneNumber, v))
}

// PhoneNumberGTE applies the GTE predicate on the "phone_number" field.
func PhoneNumberGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldPhoneNumber, v))
}

// PhoneNumberLT applies the LT predicate on the "phone_number" field.
func PhoneNumberLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldPhoneNumber, v))
}

// PhoneNumberLTE applies the LTE predicate on the "phone_number" field.
func PhoneNumberLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldPhoneNumber, v))
}

// PhoneNumberContains applies the Contains predicate on the "phone_number" field.
func PhoneNumberContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldPhoneNumber, v))
}

// PhoneNumberHasPrefix applies the HasPrefix predicate on the "phone_number" field.
func PhoneNumberHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldPhoneNumber, v))
}

// PhoneNumberHasSuffix applies the HasSuffix predicate on the "phone_number" field.
func PhoneNumberHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldPhoneNumber, v))
}

// PhoneNumberEqualFold applies the EqualFold predicate on the "phone_number" field.
func PhoneNumberEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldPhoneNumber, v))
}

// PhoneNumberContainsFold applies the ContainsFold predicate on the "phone_number" field.
func PhoneNumberContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldPhoneNumber, v))
}

// SmsContentEQ applies the EQ predicate on the "sms_content" field.
func SmsContentEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldSmsContent, v))
}

// SmsContentNEQ applies the NEQ predicate on the "sms_content" field.
func SmsContentNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldSmsContent, v))
}

// SmsContentIn applies the In predicate on the "sms_content" field.
func SmsContentIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldSmsContent, vs...))
}

// SmsContentNotIn applies the NotIn predicate on the "sms_content" field.
func SmsContentNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldSmsContent, vs...))
}

// SmsContentGT applies the GT predicate on the "sms_content" field.
func SmsContentGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldSmsContent, v))
}

// SmsContentGTE applies the GTE predicate on the "sms_content" field.
func SmsContentGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldSmsContent, v))
}

// SmsContentLT applies the LT predicate on the "sms_content" field.
func SmsContentLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldSmsContent, v))
}

// SmsContentLTE applies the LTE predicate on the "sms_content" field.
func SmsContentLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldSmsContent, v))
}

// SmsContentContains applies the Contains predicate on the "sms_content" field.
func SmsContentContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldSmsContent, v))
}

// SmsContentHasPrefix applies the HasPrefix predicate on the "sms_content" field.
func SmsContentHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldSmsContent, v))
}

// SmsContentHasSuffix applies the HasSuffix predicate on the "sms_content" field.
func SmsContentHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldSmsContent, v))
}

// SmsContentIsNil applies the IsNil predicate on the "sms_content" field.
func SmsContentIsNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIsNull(FieldSmsContent))
}

// SmsContentNotNil applies the NotNil predicate on the "sms_content" field.
func SmsContentNotNil() predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotNull(FieldSmsContent))
}

// SmsContentEqualFold applies the EqualFold predicate on the "sms_content" field.
func SmsContentEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldSmsContent, v))
}

// SmsContentContainsFold applies the ContainsFold predicate on the "sms_content" field.
func SmsContentContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldSmsContent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SmsOrder {
	return predicate.SmsOrder(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SmsOrder) predicate.SmsOrder {
	return predicate.SmsOrder(sql.NotPredicates(p))
}
