// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/smsorder"
)

// SmsOrderCreate is the builder for creating a SmsOrder entity.
type SmsOrderCreate struct {
	config
	mutation *SmsOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SmsOrderCreate) SetCreatedAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableCreatedAt(v *time.Time) *SmsOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SmsOrderCreate) SetUpdatedAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableUpdatedAt(v *time.Time) *SmsOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *SmsOrderCreate) SetOrderNo(v string) *SmsOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *SmsOrderCreate) SetPhoneNumber(v string) *SmsOrderCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillablePhoneNumber(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetPhoneNumber(*v)
	}
	return _c
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (_c *SmsOrderCreate) SetHeroSmsID(v string) *SmsOrderCreate {
	_c.mutation.SetHeroSmsID(v)
	return _c
}

// SetNillableHeroSmsID sets the "hero_sms_id" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableHeroSmsID(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetHeroSmsID(*v)
	}
	return _c
}

// SetSmsContent sets the "sms_content" field.
func (_c *SmsOrderCreate) SetSmsContent(v string) *SmsOrderCreate {
	_c.mutation.SetSmsContent(v)
	return _c
}

// SetNillableSmsContent sets the "sms_content" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableSmsContent(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetSmsContent(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SmsOrderCreate) SetStatus(v string) *SmsOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillableStatus(v *string) *SmsOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPendingAt sets the "pending_at" field.
func (_c *SmsOrderCreate) SetPendingAt(v time.Time) *SmsOrderCreate {
	_c.mutation.SetPendingAt(v)
	return _c
}

// SetNillablePendingAt sets the "pending_at" field if the given value is not nil.
func (_c *SmsOrderCreate) SetNillablePendingAt(v *time.Time) *SmsOrderCreate {
	if v != nil {
		_c.SetPendingAt(*v)
	}
	return _c
}

// Mutation returns the SmsOrderMutation object of the builder.
func (_c *SmsOrderCreate) Mutation() *SmsOrderMutation {
	return _c.mutation
}

// Save creates the SmsOrder in the database.
func (_c *SmsOrderCreate) Save(ctx context.Context) (*SmsOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SmsOrderCreate) SaveX(ctx context.Context) *SmsOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SmsOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SmsOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SmsOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := smsorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := smsorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PhoneNumber(); !ok {
		v := smsorder.DefaultPhoneNumber
		_c.mutation.SetPhoneNumber(v)
	}
	if _, ok := _c.mutation.HeroSmsID(); !ok {
		v := smsorder.DefaultHeroSmsID
		_c.mutation.SetHeroSmsID(v)
	}
	if _, ok := _c.mutation.SmsContent(); !ok {
		v := smsorder.DefaultSmsContent
		_c.mutation.SetSmsContent(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := smsorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SmsOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SmsOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SmsOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "SmsOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := smsorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PhoneNumber(); ok {
		if err := smsorder.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.phone_number": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HeroSmsID(); ok {
		if err := smsorder.HeroSmsIDValidator(v); err != nil {
			return &ValidationError{Name: "hero_sms_id", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.hero_sms_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SmsOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := smsorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_c *SmsOrderCreate) sqlSave(ctx context.Context) (*SmsOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SmsOrderCreate) createSpec() (*SmsOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SmsOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(smsorder.Table, sqlgraph.NewFieldSpec(smsorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(smsorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(smsorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(smsorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(smsorder.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.HeroSmsID(); ok {
		_spec.SetField(smsorder.FieldHeroSmsID, field.TypeString, value)
		_node.HeroSmsID = value
	}
	if value, ok := _c.mutation.SmsContent(); ok {
		_spec.SetField(smsorder.FieldSmsContent, field.TypeString, value)
		_node.SmsContent = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(smsorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PendingAt(); ok {
		_spec.SetField(smsorder.FieldPendingAt, field.TypeTime, value)
		_node.PendingAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SmsOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SmsOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SmsOrderCreate) OnConflict(opts ...sql.ConflictOption) *SmsOrderUpsertOne {
	_c.conflict = opts
	return &SmsOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SmsOrderCreate) OnConflictColumns(columns ...string) *SmsOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SmsOrderUpsertOne{
		create: _c,
	}
}

type (
	// SmsOrderUpsertOne is the builder for "upsert"-ing
	//  one SmsOrder node.
	SmsOrderUpsertOne struct {
		create *SmsOrderCreate
	}

	// SmsOrderUpsert is the "OnConflict" setter.
	SmsOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsert) SetUpdatedAt(v time.Time) *SmsOrderUpsert {
	u.Set(smsorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateUpdatedAt() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *SmsOrderUpsert) SetOrderNo(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateOrderNo() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldOrderNo)
	return u
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsert) SetPhoneNumber(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldPhoneNumber, v)
	return u
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdatePhoneNumber() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldPhoneNumber)
	return u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (u *SmsOrderUpsert) ClearPhoneNumber() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldPhoneNumber)
	return u
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (u *SmsOrderUpsert) SetHeroSmsID(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldHeroSmsID, v)
	return u
}

// UpdateHeroSmsID sets the "hero_sms_id" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateHeroSmsID() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldHeroSmsID)
	return u
}

// ClearHeroSmsID clears the value of the "hero_sms_id" field.
func (u *SmsOrderUpsert) ClearHeroSmsID() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldHeroSmsID)
	return u
}

// SetSmsContent sets the "sms_content" field.
func (u *SmsOrderUpsert) SetSmsContent(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldSmsContent, v)
	return u
}

// UpdateSmsContent sets the "sms_content" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateSmsContent() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldSmsContent)
	return u
}

// ClearSmsContent clears the value of the "sms_content" field.
func (u *SmsOrderUpsert) ClearSmsContent() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldSmsContent)
	return u
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsert) SetStatus(v string) *SmsOrderUpsert {
	u.Set(smsorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdateStatus() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldStatus)
	return u
}

// SetPendingAt sets the "pending_at" field.
func (u *SmsOrderUpsert) SetPendingAt(v time.Time) *SmsOrderUpsert {
	u.Set(smsorder.FieldPendingAt, v)
	return u
}

// UpdatePendingAt sets the "pending_at" field to the value that was provided on create.
func (u *SmsOrderUpsert) UpdatePendingAt() *SmsOrderUpsert {
	u.SetExcluded(smsorder.FieldPendingAt)
	return u
}

// ClearPendingAt clears the value of the "pending_at" field.
func (u *SmsOrderUpsert) ClearPendingAt() *SmsOrderUpsert {
	u.SetNull(smsorder.FieldPendingAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SmsOrderUpsertOne) UpdateNewValues() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(smsorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SmsOrderUpsertOne) Ignore() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SmsOrderUpsertOne) DoNothing() *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SmsOrderCreate.OnConflict
// documentation for more info.
func (u *SmsOrderUpsertOne) Update(set func(*SmsOrderUpsert)) *SmsOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SmsOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsertOne) SetUpdatedAt(v time.Time) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateUpdatedAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *SmsOrderUpsertOne) SetOrderNo(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateOrderNo() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsertOne) SetPhoneNumber(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPhoneNumber(v)
	})
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdatePhoneNumber() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePhoneNumber()
	})
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (u *SmsOrderUpsertOne) ClearPhoneNumber() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearPhoneNumber()
	})
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (u *SmsOrderUpsertOne) SetHeroSmsID(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetHeroSmsID(v)
	})
}

// UpdateHeroSmsID sets the "hero_sms_id" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateHeroSmsID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateHeroSmsID()
	})
}

// ClearHeroSmsID clears the value of the "hero_sms_id" field.
func (u *SmsOrderUpsertOne) ClearHeroSmsID() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearHeroSmsID()
	})
}

// SetSmsContent sets the "sms_content" field.
func (u *SmsOrderUpsertOne) SetSmsContent(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSmsContent(v)
	})
}

// UpdateSmsContent sets the "sms_content" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateSmsContent() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSmsContent()
	})
}

// ClearSmsContent clears the value of the "sms_content" field.
func (u *SmsOrderUpsertOne) ClearSmsContent() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearSmsContent()
	})
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsertOne) SetStatus(v string) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdateStatus() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPendingAt sets the "pending_at" field.
func (u *SmsOrderUpsertOne) SetPendingAt(v time.Time) *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPendingAt(v)
	})
}

// UpdatePendingAt sets the "pending_at" field to the value that was provided on create.
func (u *SmsOrderUpsertOne) UpdatePendingAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePendingAt()
	})
}

// ClearPendingAt clears the value of the "pending_at" field.
func (u *SmsOrderUpsertOne) ClearPendingAt() *SmsOrderUpsertOne {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearPendingAt()
	})
}

// Exec executes the query.
func (u *SmsOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SmsOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SmsOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SmsOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SmsOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SmsOrderCreateBulk is the builder for creating many SmsOrder entities in bulk.
type SmsOrderCreateBulk struct {
	config
	err      error
	builders []*SmsOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the SmsOrder entities in the database.
func (_c *SmsOrderCreateBulk) Save(ctx context.Context) ([]*SmsOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SmsOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SmsOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SmsOrderCreateBulk) SaveX(ctx context.Context) []*SmsOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SmsOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SmsOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SmsOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SmsOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SmsOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SmsOrderUpsertBulk {
	_c.conflict = opts
	return &SmsOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SmsOrderCreateBulk) OnConflictColumns(columns ...string) *SmsOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SmsOrderUpsertBulk{
		create: _c,
	}
}

// SmsOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of SmsOrder nodes.
type SmsOrderUpsertBulk struct {
	create *SmsOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SmsOrderUpsertBulk) UpdateNewValues() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(smsorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SmsOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SmsOrderUpsertBulk) Ignore() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SmsOrderUpsertBulk) DoNothing() *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SmsOrderCreateBulk.OnConflict
// documentation for more info.
func (u *SmsOrderUpsertBulk) Update(set func(*SmsOrderUpsert)) *SmsOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SmsOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SmsOrderUpsertBulk) SetUpdatedAt(v time.Time) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateUpdatedAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *SmsOrderUpsertBulk) SetOrderNo(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateOrderNo() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetPhoneNumber sets the "phone_number" field.
func (u *SmsOrderUpsertBulk) SetPhoneNumber(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPhoneNumber(v)
	})
}

// UpdatePhoneNumber sets the "phone_number" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdatePhoneNumber() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePhoneNumber()
	})
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (u *SmsOrderUpsertBulk) ClearPhoneNumber() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearPhoneNumber()
	})
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (u *SmsOrderUpsertBulk) SetHeroSmsID(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetHeroSmsID(v)
	})
}

// UpdateHeroSmsID sets the "hero_sms_id" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateHeroSmsID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateHeroSmsID()
	})
}

// ClearHeroSmsID clears the value of the "hero_sms_id" field.
func (u *SmsOrderUpsertBulk) ClearHeroSmsID() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearHeroSmsID()
	})
}

// SetSmsContent sets the "sms_content" field.
func (u *SmsOrderUpsertBulk) SetSmsContent(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetSmsContent(v)
	})
}

// UpdateSmsContent sets the "sms_content" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateSmsContent() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateSmsContent()
	})
}

// ClearSmsContent clears the value of the "sms_content" field.
func (u *SmsOrderUpsertBulk) ClearSmsContent() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearSmsContent()
	})
}

// SetStatus sets the "status" field.
func (u *SmsOrderUpsertBulk) SetStatus(v string) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdateStatus() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPendingAt sets the "pending_at" field.
func (u *SmsOrderUpsertBulk) SetPendingAt(v time.Time) *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.SetPendingAt(v)
	})
}

// UpdatePendingAt sets the "pending_at" field to the value that was provided on create.
func (u *SmsOrderUpsertBulk) UpdatePendingAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.UpdatePendingAt()
	})
}

// ClearPendingAt clears the value of the "pending_at" field.
func (u *SmsOrderUpsertBulk) ClearPendingAt() *SmsOrderUpsertBulk {
	return u.Update(func(s *SmsOrderUpsert) {
		s.ClearPendingAt()
	})
}

// Exec executes the query.
func (u *SmsOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SmsOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SmsOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SmsOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
