// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/smsorder"
)

// SmsOrderUpdate is the builder for updating SmsOrder entities.
type SmsOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SmsOrderMutation
}

// Where appends a list predicates to the SmsOrderUpdate builder.
func (_u *SmsOrderUpdate) Where(ps ...predicate.SmsOrder) *SmsOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SmsOrderUpdate) SetUpdatedAt(v time.Time) *SmsOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *SmsOrderUpdate) SetOrderNo(v string) *SmsOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillableOrderNo(v *string) *SmsOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *SmsOrderUpdate) SetPhoneNumber(v string) *SmsOrderUpdate {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillablePhoneNumber(v *string) *SmsOrderUpdate {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *SmsOrderUpdate) ClearPhoneNumber() *SmsOrderUpdate {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (_u *SmsOrderUpdate) SetHeroSmsID(v string) *SmsOrderUpdate {
	_u.mutation.SetHeroSmsID(v)
	return _u
}

// SetNillableHeroSmsID sets the "hero_sms_id" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillableHeroSmsID(v *string) *SmsOrderUpdate {
	if v != nil {
		_u.SetHeroSmsID(*v)
	}
	return _u
}

// ClearHeroSmsID clears the value of the "hero_sms_id" field.
func (_u *SmsOrderUpdate) ClearHeroSmsID() *SmsOrderUpdate {
	_u.mutation.ClearHeroSmsID()
	return _u
}

// SetSmsContent sets the "sms_content" field.
func (_u *SmsOrderUpdate) SetSmsContent(v string) *SmsOrderUpdate {
	_u.mutation.SetSmsContent(v)
	return _u
}

// SetNillableSmsContent sets the "sms_content" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillableSmsContent(v *string) *SmsOrderUpdate {
	if v != nil {
		_u.SetSmsContent(*v)
	}
	return _u
}

// ClearSmsContent clears the value of the "sms_content" field.
func (_u *SmsOrderUpdate) ClearSmsContent() *SmsOrderUpdate {
	_u.mutation.ClearSmsContent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SmsOrderUpdate) SetStatus(v string) *SmsOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillableStatus(v *string) *SmsOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPendingAt sets the "pending_at" field.
func (_u *SmsOrderUpdate) SetPendingAt(v time.Time) *SmsOrderUpdate {
	_u.mutation.SetPendingAt(v)
	return _u
}

// SetNillablePendingAt sets the "pending_at" field if the given value is not nil.
func (_u *SmsOrderUpdate) SetNillablePendingAt(v *time.Time) *SmsOrderUpdate {
	if v != nil {
		_u.SetPendingAt(*v)
	}
	return _u
}

// ClearPendingAt clears the value of the "pending_at" field.
func (_u *SmsOrderUpdate) ClearPendingAt() *SmsOrderUpdate {
	_u.mutation.ClearPendingAt()
	return _u
}

// Mutation returns the SmsOrderMutation object of the builder.
func (_u *SmsOrderUpdate) Mutation() *SmsOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SmsOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SmsOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SmsOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SmsOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SmsOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := smsorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SmsOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := smsorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := smsorder.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeroSmsID(); ok {
		if err := smsorder.HeroSmsIDValidator(v); err != nil {
			return &ValidationError{Name: "hero_sms_id", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.hero_sms_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := smsorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SmsOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smsorder.Table, smsorder.Columns, sqlgraph.NewFieldSpec(smsorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(smsorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(smsorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(smsorder.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(smsorder.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.HeroSmsID(); ok {
		_spec.SetField(smsorder.FieldHeroSmsID, field.TypeString, value)
	}
	if _u.mutation.HeroSmsIDCleared() {
		_spec.ClearField(smsorder.FieldHeroSmsID, field.TypeString)
	}
	if value, ok := _u.mutation.SmsContent(); ok {
		_spec.SetField(smsorder.FieldSmsContent, field.TypeString, value)
	}
	if _u.mutation.SmsContentCleared() {
		_spec.ClearField(smsorder.FieldSmsContent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(smsorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingAt(); ok {
		_spec.SetField(smsorder.FieldPendingAt, field.TypeTime, value)
	}
	if _u.mutation.PendingAtCleared() {
		_spec.ClearField(smsorder.FieldPendingAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smsorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SmsOrderUpdateOne is the builder for updating a single SmsOrder entity.
type SmsOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SmsOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SmsOrderUpdateOne) SetUpdatedAt(v time.Time) *SmsOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *SmsOrderUpdateOne) SetOrderNo(v string) *SmsOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillableOrderNo(v *string) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *SmsOrderUpdateOne) SetPhoneNumber(v string) *SmsOrderUpdateOne {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillablePhoneNumber(v *string) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *SmsOrderUpdateOne) ClearPhoneNumber() *SmsOrderUpdateOne {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetHeroSmsID sets the "hero_sms_id" field.
func (_u *SmsOrderUpdateOne) SetHeroSmsID(v string) *SmsOrderUpdateOne {
	_u.mutation.SetHeroSmsID(v)
	return _u
}

// SetNillableHeroSmsID sets the "hero_sms_id" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillableHeroSmsID(v *string) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetHeroSmsID(*v)
	}
	return _u
}

// ClearHeroSmsID clears the value of the "hero_sms_id" field.
func (_u *SmsOrderUpdateOne) ClearHeroSmsID() *SmsOrderUpdateOne {
	_u.mutation.ClearHeroSmsID()
	return _u
}

// SetSmsContent sets the "sms_content" field.
func (_u *SmsOrderUpdateOne) SetSmsContent(v string) *SmsOrderUpdateOne {
	_u.mutation.SetSmsContent(v)
	return _u
}

// SetNillableSmsContent sets the "sms_content" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillableSmsContent(v *string) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetSmsContent(*v)
	}
	return _u
}

// ClearSmsContent clears the value of the "sms_content" field.
func (_u *SmsOrderUpdateOne) ClearSmsContent() *SmsOrderUpdateOne {
	_u.mutation.ClearSmsContent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SmsOrderUpdateOne) SetStatus(v string) *SmsOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillableStatus(v *string) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPendingAt sets the "pending_at" field.
func (_u *SmsOrderUpdateOne) SetPendingAt(v time.Time) *SmsOrderUpdateOne {
	_u.mutation.SetPendingAt(v)
	return _u
}

// SetNillablePendingAt sets the "pending_at" field if the given value is not nil.
func (_u *SmsOrderUpdateOne) SetNillablePendingAt(v *time.Time) *SmsOrderUpdateOne {
	if v != nil {
		_u.SetPendingAt(*v)
	}
	return _u
}

// ClearPendingAt clears the value of the "pending_at" field.
func (_u *SmsOrderUpdateOne) ClearPendingAt() *SmsOrderUpdateOne {
	_u.mutation.ClearPendingAt()
	return _u
}

// Mutation returns the SmsOrderMutation object of the builder.
func (_u *SmsOrderUpdateOne) Mutation() *SmsOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the SmsOrderUpdate builder.
func (_u *SmsOrderUpdateOne) Where(ps ...predicate.SmsOrder) *SmsOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SmsOrderUpdateOne) Select(field string, fields ...string) *SmsOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SmsOrder entity.
func (_u *SmsOrderUpdateOne) Save(ctx context.Context) (*SmsOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SmsOrderUpdateOne) SaveX(ctx context.Context) *SmsOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SmsOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SmsOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SmsOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := smsorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SmsOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := smsorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := smsorder.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HeroSmsID(); ok {
		if err := smsorder.HeroSmsIDValidator(v); err != nil {
			return &ValidationError{Name: "hero_sms_id", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.hero_sms_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := smsorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SmsOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SmsOrderUpdateOne) sqlSave(ctx context.Context) (_node *SmsOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smsorder.Table, smsorder.Columns, sqlgraph.NewFieldSpec(smsorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SmsOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smsorder.FieldID)
		for _, f := range fields {
			if !smsorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != smsorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(smsorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(smsorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(smsorder.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(smsorder.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.HeroSmsID(); ok {
		_spec.SetField(smsorder.FieldHeroSmsID, field.TypeString, value)
	}
	if _u.mutation.HeroSmsIDCleared() {
		_spec.ClearField(smsorder.FieldHeroSmsID, field.TypeString)
	}
	if value, ok := _u.mutation.SmsContent(); ok {
		_spec.SetField(smsorder.FieldSmsContent, field.TypeString, value)
	}
	if _u.mutation.SmsContentCleared() {
		_spec.ClearField(smsorder.FieldSmsContent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(smsorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingAt(); ok {
		_spec.SetField(smsorder.FieldPendingAt, field.TypeTime, value)
	}
	if _u.mutation.PendingAtCleared() {
		_spec.ClearField(smsorder.FieldPendingAt, field.TypeTime)
	}
	_node = &SmsOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smsorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
